# Testing of the mcmc_utils Module

In [1]:
from hit_and_run_uniform_slice_sampling import parallel_hruss
import mcmc_utils as mcu

In [2]:
import numpy as np
import numpy.linalg as alg
import numpy.random as rnd

In [3]:
verbose = False # basically whether to print each function's docstring before testing it

## Generate Samples and TDE to Analyze

In [4]:
d = 17
def log_density(x):
    return -alg.norm(x)

In [5]:
n_its_1 = int(1e4)
n_chains_1 = 10
w_1 = d
x_0s_1 = rnd.normal(size=(n_chains_1,d))

In [6]:
samples_1, tde_1 = parallel_hruss(log_density, n_chains_1, n_its_1, x_0s_1, w_1)

Checking validity of given arguments...
Preparing for parallel sampling...
Starting parallel sampling...


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 10000/10000 [00:00<00:00, 27568.30it/s]


Processing returns and terminating...


In [7]:
samples_1.shape

(10001, 10, 17)

In [8]:
n_its_2 = int(1.1e4)
n_chains_2 = 9
w_2 = d
x_0s_2 = rnd.normal(size=(n_chains_2,d))

In [9]:
samples_2, tde_2 = parallel_hruss(log_density, n_chains_2, n_its_2, x_0s_2, w_2)

Checking validity of given arguments...
Preparing for parallel sampling...
Starting parallel sampling...


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 11000/11000 [00:00<00:00, 19571.85it/s]


Processing returns and terminating...


In [10]:
samples_2.shape

(11001, 9, 17)

In [11]:
samples = [samples_1, samples_2]
tde = [tde_1, tde_2]
samples_c0 = [sams[:,0] for sams in samples]

## Test the mcmc_utils Module by Analyzing the Samples and TDE

In [12]:
if verbose:
    print(mcu.__doc__)

### Computing Radii

In [13]:
if verbose:
    print(mcu.get_radii.__doc__)

In [14]:
radii_1_c0 = mcu.get_radii(samples_1[:,0])
print(radii_1_c0.shape)
radii_1_c0

(10001,)


array([ 3.30121271,  2.86542096,  2.81491049, ..., 17.02614894,
       17.15759545, 17.1329186 ])

In [15]:
radii_1 = mcu.get_radii(samples_1)
print(radii_1.shape)
radii_1

(10001, 10)


array([[ 3.30121271,  3.31354475,  2.88198154, ...,  3.39510039,
         3.77621428,  3.46710052],
       [ 2.86542096,  3.57659554,  3.12267034, ...,  3.40667909,
         3.60061084,  4.05466369],
       [ 2.81491049,  3.83035753,  3.17493694, ...,  3.77977779,
         3.60146757,  3.32130988],
       ...,
       [17.02614894, 25.14758226, 24.85021967, ..., 25.23843203,
        17.65916894, 15.31633824],
       [17.15759545, 24.6451341 , 23.63718634, ..., 25.52379062,
        17.67131561, 14.76506936],
       [17.1329186 , 23.69560645, 23.47306839, ..., 24.57572784,
        18.19433235, 14.81188799]])

In [16]:
if verbose:
    print(mcu.get_radii_list.__doc__)

In [17]:
radii_c0 = mcu.get_radii_list(samples_c0)
for rs in radii_c0:
    print(rs.shape)
radii_c0

(10001,)
(11001,)


[array([ 3.30121271,  2.86542096,  2.81491049, ..., 17.02614894,
        17.15759545, 17.1329186 ]),
 array([ 3.50635743,  3.51050286,  4.09384405, ..., 24.8654013 ,
        24.39023075, 24.57737426])]

In [18]:
radii = mcu.get_radii_list(samples)
for rs in radii:
    print(rs.shape)
radii

(10001, 10)
(11001, 9)


[array([[ 3.30121271,  3.31354475,  2.88198154, ...,  3.39510039,
          3.77621428,  3.46710052],
        [ 2.86542096,  3.57659554,  3.12267034, ...,  3.40667909,
          3.60061084,  4.05466369],
        [ 2.81491049,  3.83035753,  3.17493694, ...,  3.77977779,
          3.60146757,  3.32130988],
        ...,
        [17.02614894, 25.14758226, 24.85021967, ..., 25.23843203,
         17.65916894, 15.31633824],
        [17.15759545, 24.6451341 , 23.63718634, ..., 25.52379062,
         17.67131561, 14.76506936],
        [17.1329186 , 23.69560645, 23.47306839, ..., 24.57572784,
         18.19433235, 14.81188799]]),
 array([[ 3.50635743,  3.41509987,  4.07370203, ...,  3.4981584 ,
          4.83075335,  5.23559849],
        [ 3.51050286,  3.37980155,  5.10910314, ...,  3.64238259,
          4.75293297,  5.42249581],
        [ 4.09384405,  3.4934531 ,  5.44056774, ...,  3.64300864,
          4.79549716,  5.4347818 ],
        ...,
        [24.8654013 , 15.2325726 , 21.99019326, ..., 1

### Computing Log Radii

In [19]:
if verbose:
    print(mcu.get_log_radii.__doc__)

In [20]:
log_radii_1_c0 = mcu.get_log_radii(samples_1[:,0])
print(log_radii_1_c0.shape)
log_radii_1_c0

(10001,)


array([1.19428989, 1.05271527, 1.03493046, ..., 2.83475034, 2.84244096,
       2.84100168])

In [21]:
log_radii_1 = mcu.get_log_radii(samples_1)
print(log_radii_1.shape)
log_radii_1

(10001, 10)


array([[1.19428989, 1.19801854, 1.05847809, ..., 1.22233333, 1.32872199,
        1.24331866],
       [1.05271527, 1.27441138, 1.13868851, ..., 1.22573794, 1.28110351,
        1.39986775],
       [1.03493046, 1.34295815, 1.15528777, ..., 1.32966522, 1.28134142,
        1.20035925],
       ...,
       [2.83475034, 3.22476176, 3.21286659, ..., 3.22836791, 2.87125514,
        2.72892012],
       [2.84244096, 3.20457948, 3.16282116, ..., 3.23961098, 2.87194274,
        2.69226421],
       [2.84100168, 3.16528965, 3.15585374, ..., 3.20175928, 2.90111014,
        2.6954301 ]])

In [22]:
if verbose:
    print(mcu.get_log_radii_list.__doc__)

In [23]:
log_radii_c0 = mcu.get_log_radii_list(samples_c0)
for rs in log_radii_c0:
    print(rs.shape)
log_radii_c0

(10001,)
(11001,)


[array([1.19428989, 1.05271527, 1.03493046, ..., 2.83475034, 2.84244096,
        2.84100168]),
 array([1.25457773, 1.25575929, 1.40948439, ..., 3.21347733, 3.19418267,
        3.20182627])]

In [24]:
log_radii = mcu.get_log_radii_list(samples)
for rs in log_radii:
    print(rs.shape)
log_radii

(10001, 10)
(11001, 9)


[array([[1.19428989, 1.19801854, 1.05847809, ..., 1.22233333, 1.32872199,
         1.24331866],
        [1.05271527, 1.27441138, 1.13868851, ..., 1.22573794, 1.28110351,
         1.39986775],
        [1.03493046, 1.34295815, 1.15528777, ..., 1.32966522, 1.28134142,
         1.20035925],
        ...,
        [2.83475034, 3.22476176, 3.21286659, ..., 3.22836791, 2.87125514,
         2.72892012],
        [2.84244096, 3.20457948, 3.16282116, ..., 3.23961098, 2.87194274,
         2.69226421],
        [2.84100168, 3.16528965, 3.15585374, ..., 3.20175928, 2.90111014,
         2.6954301 ]]),
 array([[1.25457773, 1.22820674, 1.40455218, ..., 1.25223666, 1.57500243,
         1.65548116],
        [1.25575929, 1.21781699, 1.63102388, ..., 1.29263803, 1.55876189,
         1.69055619],
        [1.40948439, 1.25089067, 1.69388342, ..., 1.29280989, 1.56767739,
         1.69281937],
        ...,
        [3.21347733, 2.72343607, 3.09059659, ..., 2.78706128, 2.69353282,
         2.63485821],
        [3.1

### Computing Step Sizes

In [25]:
if verbose:
    print(mcu.get_steps.__doc__)

In [26]:
steps_1_c0 = mcu.get_steps(samples_1[:,0])
print(steps_1_c0.shape)
steps_1_c0

(10000,)


array([2.1267077 , 0.4946511 , 0.53677063, ..., 2.74393675, 0.66700397,
       8.69224062])

In [27]:
steps_1 = mcu.get_steps(samples_1)
print(steps_1.shape)
steps_1

(10000, 10)


array([[2.12670770e+00, 3.73556011e+00, 8.20738014e-01, ...,
        2.41426521e-01, 3.01424980e+00, 2.42912880e+00],
       [4.94651099e-01, 1.21623664e+00, 2.31316989e+00, ...,
        1.61881459e+00, 1.53302449e-02, 2.57436454e+00],
       [5.36770632e-01, 5.40190582e+00, 1.20998106e+00, ...,
        2.52570041e+00, 1.98680679e+00, 5.20699380e-01],
       ...,
       [2.74393675e+00, 2.54066507e+00, 1.22132375e+01, ...,
        8.09356710e+00, 1.94280493e+00, 1.08508793e+00],
       [6.67003970e-01, 1.26767090e+01, 3.35377876e+00, ...,
        9.17315052e-01, 3.53632465e-01, 9.85619497e+00],
       [8.69224062e+00, 1.76754423e+01, 5.57389434e+00, ...,
        1.37298377e+00, 3.44401006e+00, 1.57308267e-01]])

In [28]:
if verbose:
    print(mcu.get_steps_list.__doc__)

In [29]:
steps_c0 = mcu.get_steps_list(samples_c0)
for sts in steps_c0:
    print(sts.shape)
steps_c0

(10000,)
(11000,)


[array([2.1267077 , 0.4946511 , 0.53677063, ..., 2.74393675, 0.66700397,
        8.69224062]),
 array([ 0.19301657,  2.17714552,  2.15062444, ..., 11.91381335,
         7.74729673,  1.65875523])]

In [30]:
steps = mcu.get_steps_list(samples)
for sts in steps:
    print(sts.shape)
steps

(10000, 10)
(11000, 9)


[array([[2.12670770e+00, 3.73556011e+00, 8.20738014e-01, ...,
         2.41426521e-01, 3.01424980e+00, 2.42912880e+00],
        [4.94651099e-01, 1.21623664e+00, 2.31316989e+00, ...,
         1.61881459e+00, 1.53302449e-02, 2.57436454e+00],
        [5.36770632e-01, 5.40190582e+00, 1.20998106e+00, ...,
         2.52570041e+00, 1.98680679e+00, 5.20699380e-01],
        ...,
        [2.74393675e+00, 2.54066507e+00, 1.22132375e+01, ...,
         8.09356710e+00, 1.94280493e+00, 1.08508793e+00],
        [6.67003970e-01, 1.26767090e+01, 3.35377876e+00, ...,
         9.17315052e-01, 3.53632465e-01, 9.85619497e+00],
        [8.69224062e+00, 1.76754423e+01, 5.57389434e+00, ...,
         1.37298377e+00, 3.44401006e+00, 1.57308267e-01]]),
 array([[ 0.19301657,  0.65755271,  3.64515681, ...,  0.9505214 ,
          0.7831039 ,  2.62220526],
        [ 2.17714552,  1.61721641,  2.80507564, ...,  0.05470374,
          2.62826887,  0.03962107],
        [ 2.15062444,  1.2863014 ,  2.04012836, ...,  3.97595

In [31]:
if verbose:
    print(mcu.get_flat_steps.__doc__)

In [32]:
flat_steps_1 = mcu.get_flat_steps(samples_1)
print(flat_steps_1.shape)
flat_steps_1

(100000,)


array([2.1267077 , 3.73556011, 0.82073801, ..., 1.37298377, 3.44401006,
       0.15730827])

In [33]:
if verbose:
    print(mcu.get_flat_steps_list.__doc__)

In [34]:
flat_steps = mcu.get_flat_steps_list(samples)
for sts in flat_steps:
    print(sts.shape)
flat_steps

(100000,)
(99000,)


[array([2.1267077 , 3.73556011, 0.82073801, ..., 1.37298377, 3.44401006,
        0.15730827]),
 array([0.19301657, 0.65755271, 3.64515681, ..., 3.69467082, 1.30253297,
        2.43628672])]

### Computing Mean TDE for a List

In [35]:
if verbose:
    print(mcu.mean_tde_list.__doc__)

In [36]:
mean_tde = mcu.mean_tde_list(tde)
mean_tde

array([4.86725327, 4.85821491])

### Computing MSS

In [37]:
if verbose:
    print(mcu.mss.__doc__)

In [38]:
mss_1_c0 = mcu.mss(samples_1[:,0])
mss_1_c0

4.422898895410969

In [39]:
mss_1 = mcu.mss(samples_1)
mss_1

4.42376487747069

In [40]:
if verbose:
    print(mcu.mss_list.__doc__)

In [41]:
mss_c0 = mcu.mss_list(samples_c0)
mss_c0

array([4.4228989, 4.5133014])

In [42]:
mss = mcu.mss_list(samples)
mss

array([4.42376488, 4.49770515])

### (mean) IAT

In [43]:
maxl = 1234
maxls = [maxl, 2*maxl]

In [44]:
if verbose:
    print(mcu.iat.__doc__)

In [45]:
iat_1_c0_d0 = mcu.iat(samples_1[:,0,0], maxl)
iat_1_c0_d0

32.97127687458932

In [46]:
if verbose:
    print(mcu.iat_list.__doc__)

In [47]:
iat_c0_d0 = mcu.iat_list([sams[:,0] for sams in samples_c0], maxls)
iat_c0_d0

array([32.97127687, 38.51062631])

In [48]:
if verbose:
    print(mcu.iat_multi_chain.__doc__)

In [49]:
iat_1_d0 = mcu.iat_multi_chain(samples_1[:,:,0], maxl)
iat_1_d0

33.07339466848005

In [50]:
if verbose:
    print(mcu.iat_multi_chain_list.__doc__)

In [51]:
iat_d0 = mcu.iat_multi_chain_list([sams[:,:,0] for sams in samples], maxls)
iat_d0

array([33.07339467, 30.90128557])

In [52]:
if verbose:
    print(mcu.mean_iat.__doc__)

In [53]:
mean_iat_1_c0 = mcu.mean_iat(samples_1[:,0], maxl)
mean_iat_1_c0

33.68865291186715

In [54]:
if verbose:
    print(mcu.mean_iat_list.__doc__)

In [55]:
mean_iat_c0 = mcu.mean_iat_list(samples_c0, maxl)
mean_iat_c0

array([33.68865291, 35.00909397])

In [56]:
if verbose:
    print(mcu.mean_iat_multi_chain.__doc__)

In [57]:
mean_iat_1 = mcu.mean_iat_multi_chain(samples_1, maxl)
mean_iat_1

34.41752780559317

In [58]:
if verbose:
    print(mcu.mean_iat_multi_chain_list.__doc__)

In [59]:
mean_iat = mcu.mean_iat_multi_chain_list(samples, maxls)
mean_iat

array([34.41752781, 34.22199155])